### PR TITLE
Explicitly depend on pywin32 on Windows

### PR DESCRIPTION
**Pull request by bastianeicher**

### CODE REVIEW

**Comment by talex5** [comment]
I made a few new releases of this in the last couple of days (trying to get Python 3 working). Some of them might need it too, but I'm not sure which. Probably 2.3.7 probably does.

2.3.8 and above are Python 3 only - not sure if that makes a difference.

**Comment by talex5** [comment]
Also, I've now remembered to push the updated master branch so you can actually see it...

**Comment by bastianeicher** [comment]
I've rebased the PR and added pygobject and pywin32 dependencies to the 2.3.8 and 2.3.9 releases.

I also removed some redundant pygobject dependencies from previous releases (inherited from parent group).

**Comment by talex5** [comment]
Ah, this isn't quite right - versions >= 2.3.8 no longer require pygobject (because they depend on Python >= 3.4, which provides asyncio, and they can use that instead).

**Comment by bastianeicher** [comment]
Ah, I see! I fixed that now.

**Pull request merged**
